name: OTF Testing
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [firefox, chrome, edge]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Selenium Preparation
        run: |
          docker run -d --network="host" -v /dev/shm:/dev/shm --name selenium-container selenium/standalone-${{ matrix.browser }}:latest
          sleep 15

      - name: Install dependencies
        run: pip install -U selenium

      - name: Run test
        run: python tests/hello_aut.py http://localhost ${{ matrix.browser }}
      
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Screenshot-${{ matrix.browser }}
          path: screenshot.png

      - name: Stop Docker
        if: always()
        run: docker stop selenium-container || true