name: OTF Testing
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [firefox, chrome, edge] 
    steps:
      - name: Run test
        run: python tests/hello_aut.py ${{ env.URL }} ${{ matrix.browser }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Screenshot-${{ matrix.browser }} 
          path: screenshot.png